language: go

sudo: false

go:
  - "1.8.x"
  - "1.9.x"
  - "1.10.x"
  - "1.11.x"
  - master

env:
  - DEP_VERSION=0.5.0

before_install:
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep

script:
  - dep ensure
  - go test -v -race $(go list ./... | grep -v vendor)
